name: spacyface
channels:
  - conda-forge
dependencies:
  - jupyter
  - pytest
  - jupyter_client
  - jupyter_console
  - jupyter_contrib_core
  - jupyter_contrib_nbextensions
  - matplotlib

name: spacyface
channels:
  - conda-forge
dependencies:
  - jupyter
  - pytest
  - jupyter_client
  - jupyter_console
  - jupyter_contrib_core
  - jupyter_contrib_nbextensions
  - matplotlib
  - seaborn
